### PR TITLE
Feature/open websites

### PR DESCRIPTION
**Pull request by nacho9900**
### Open Websites

Admins: 

- now can create website request providing an event id 
- now can approve or reject an website qr requests

Not Admins: 

- now can create a new website request or edit an existing website for an event providing an event id and the secret code for the event
- now can request more codes for an existing event

### CODE REVIEW

**Review by alavarello — COMMENTED** [review]
Add start date and end date required. When submit the website without these fields a `login required` error appears

Screenshot from 2021-08-03 14-07-26

**Comment by alavarello** [comment]
Add a message when a website was created
Screenshot from 2021-08-03 14-06-57

**Comment by alavarello** [comment]
- Fix the button style
Screenshot from 2021-08-03 14-04-00

**Comment by alavarello** [comment]
Change the name from `Manage QR Codes` to `Manage Codes`. Add a new filter for website requests and add a column that shows if it's a website

**Comment by nacho9900** [comment]
- Add Type to manage codes request page
image

**Comment by nacho9900** [comment]
>     * Fix the button style
>       Screenshot from 2021-08-03 14-04-00

- fixed
image

**Comment by nacho9900** [comment]
> Add start date and end date required. When submit the website without these fields a `login required` error appears
> 
> Screenshot from 2021-08-03 14-07-26

- done
image

**Comment by alavarello** [comment]
Can't create a website if i'm not logged in
Screenshot from 2021-08-04 09-09-55

**Comment by alavarello** [comment]
Rebase or merge the development to resolve the conflicts

**Review by alavarello — CHANGES_REQUESTED** [review]
Please read comments

**Pull request merged**
