### PR TITLE
Feature/add private property to events

### PR DESCRIPTION
**Pull request by sebasfavaron**
## Summary

Private events have been hidden for non authenticated users in app.poap.xyz/admin/events
A toggle has been added that allows creating and editing an event to be private/public (public by default)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Testing

Once the [PR](https://github.com/poap-xyz/poap-server/pull/171) that adds private events to the server is accepted, you can try create a private event, edit it and also see if as a non authenticated user you can find such private events in the list

## Ticket

[ticket for hiding private events](https://poap-devs.atlassian.net/browse/PCD-247?atlOrigin=eyJpIjoiMzkyN2MzZDhkM2MyNDkzYWFjNWRiZDMwZDg1MGVjZGIiLCJwIjoiaiJ9)
[ticket for adding private toggle on creation](https://poap-devs.atlassian.net/browse/PCD-245?atlOrigin=eyJpIjoiN2ZjMzA0OWIzZjUxNDczN2JhNzRmZmFhMDc3NTZhNjEiLCJwIjoiaiJ9)
[ticket for adding private toggle on edition](https://poap-devs.atlassian.net/browse/PCD-249?atlOrigin=eyJpIjoiOTNhNGUwZjRmZDU4NDA3NDhkMzUwYWEzYTdiZWIyOGMiLCJwIjoiaiJ9)

## Dependencies

[server PR that allows private events](https://github.com/poap-xyz/poap-server/pull/171)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I didn't commit unnecessary logs

### CODE REVIEW

**Comment by nacho9900** [comment]
`Test sebas 7` is not a private event but is not showing at the unauth list

Left AUTH / Right UNAUTH
image

**Comment by nacho9900** [comment]
`Test sebas 5` is a private event and it's showing / not showing fine at both list (auth n unauth) `PIC 1`.

But, when the event is opened to edit  as an admin, the private event checkbox is unchecked `PIC 2` . It's appears to be a backend error because the private_event field is not in the response  `PIC 3`.

PIC 1: List OK for `Test sebas 5`
image

PIC 2: Private event not checked for `Test sebas 5`
image

PIC 3: `https://dev-api.poap.xyz/events-admin/test-sebas-5-2021` response
image

**Comment by nacho9900** [comment]
**Bug**

1. Create a private event `Nacho Private Event <b>VIP</b>`.

image

2. When open to edit `private_event` field not receive.

3. Edit name to `Nacho Private Event`.

4. Save

5. The event change to public event because `private_event` was sent as `false`.

**Review by nacho9900 — APPROVED** [review]
Congrats bro!

**Review by alavarello — APPROVED** [review]

**Pull request merged**
